# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48b28a005979803422a3a843c3e4ea29033b513e43ef7d949e97dff8f8141ed36f86ad8811b2527e887c4a158315320e806196a2d98020e8b351997bc1b341a0

test:
  secret_key_base: 173e2f180d01cf772a71fc709561a4775f82f0640012fe396dde336a992b93ad04d8855fb2e170f9c4dbee368b3cd7061d4bf18ad50b4847fb6e174d1004b5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
